"""create pipeline tables

Revision ID: 065db982dca8
Revises: 
Create Date: 2026-07-23 14:04:21.670299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '065db982dca8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pipeline_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pipeline_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_id'], ['pipelines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('pipelines', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pipelines', 'schedule',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('pipelines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_pipelines_id'), table_name='pipelines')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipelines_id'), 'pipelines', ['id'], unique=False)
    op.alter_column('pipelines', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pipelines', 'schedule',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('pipelines', 'owner',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('pipeline_runs')
    # ### end Alembic commands ###
