"""create pipeline events

Revision ID: 2ad1b4bc0d1d
Revises: 20d93dfe5ab8
Create Date: 2026-07-30 14:31:36.149298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ad1b4bc0d1d'
down_revision: Union[str, Sequence[str], None] = '20d93dfe5ab8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_pipeline_events_id'), 'pipeline_events', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pipeline_events_id'), table_name='pipeline_events')
    # ### end Alembic commands ###
